### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by zsg857981535** [lavas-project/vue-skeleton-webpack-plugin#22]
照着vue-cli的那个example配置了一下，唯一的差别是用了vux-loader, 打包的时候报下面的错误，请大佬帮看下是啥问题？谢谢！

Starting to optimize CSS...
Processing static/css/main.5a5c7be868e0038b0bea389a1a89e55d.css...
Processed static/css/main.5a5c7be868e0038b0bea389a1a89e55d.css, before: 101813, after: 58680, ratio:57.64%
======== vux-loader: duplicate-style done!   ========

TypeError: Cannot read property 'split' of undefined
    at getModuleName (C:\Users\Desktop\test-skeleton\node_modules\webpack-node-externals\index.js:18:16)
    at C:\Users\Desktop\test-skeleton\node_modules\webpack-node-externals\index.js:40:26
    at handleExternals (C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:70:16)
    at C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:83:5
    at applyPluginsAsyncWaterfall (C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\NormalModuleFactory.js:236:4)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\Desktop\test-skeleton\node_modules\tapable\lib\Tapable.js:260:70)
    at NormalModuleFactory.create (C:\Users\\Desktop\test-skeleton\node_modules\webpack\lib\NormalModuleFactory.js:220:8)
    at semaphore.acquire (C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\Compilation.js:407:18)
    at Semaphore.acquire (C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\util\Semaphore.js:16:4)
    at Compilation._addModuleChain (C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\Compilation.js:406:18)
    at Compilation.addEntry (C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\Compilation.js:494:8)
    at Compiler.compiler.plugin (C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\SingleEntryPlugin.js:24:16)
    at Compiler.applyPluginsParallel (C:\Users\Desktop\test-skeleton\node_modules\tapable\lib\Tapable.js:293:14)
    at applyPluginsAsync.err (C:\Users\Desktop\test-skeleton\node_modules\webpack\lib\Compiler.js:499:9)

**Comment by feibinyang** [comment]
#11 看看这个？

**Comment by zsg857981535** [comment]
@feibinyang 感觉不是一个报错

**Comment by kenshinzzz** [comment]
我也遇到同样的报错,webpack3.
引入的插件有：
webpack.HotModuleReplacementPlugin
webpack.NamedModulesPlugin
webpack.NoEmitOnErrorsPlugin
HashedModuleIdsPlugin
webpack.optimize.CommonsChunkPlugin
InlineManifestWebpackPlugin
HtmlWebpackIncludeAssetsPlugin
ExtractTextPlugin
SkeletonWebpackPlugin
HtmlPlugin

**Comment by xiaoiver** [comment]
谢谢大家的反馈，稍后我会上传一个使用 vux-loader 的例子

**Comment by zsg857981535** [comment]
@xiaoiver 谢谢，还没传吗？example里面没有找到

**Comment by xiaoiver** [comment]
@zsg857981535 实在不好意思拖了这么久。我照着 vux 文档自己写了一个简单的，在[这里](https://github.com/xiaoiver/skeleton-demo/tree/vux)
