### ISSUE TITLE
我没有使用路由，但是routePathTemplate有一个默认值，如何将它关闭呢

### ISSUE THREAD

**Issue by martinko2009** [lavas-project/vue-skeleton-webpack-plugin#25]
```
SkeletonWebpackPlugin.loader({
    options: {
          entry: chunks,
	  importTemplate: 'import skeleton from \''+path.resolve(__dirname, './assets/components/skeleton/skeleton.vue')+'\';'
   }
 })

**Comment by martinko2009** [comment]
报错日志，如下：
```
Error: Child compilation failed:
Module build failed: SyntaxError: D:/multipage/assets/components/skeleton/lib/entry-skeleton.js: Unexpected token (1:8)

> 1 | import s{
    |         ^
  2 |             path: '/skeleton-welcome/welcome',
  3 |             name: 'skeleton-welcome/welcome',
  4 |             component: _15304950479044526b78913c1aab4524492713e5a560a
:
BabelLoaderError: SyntaxError: D:/multipage/assets/components/skeleton/lib/entry-skeleton.js: Unexpected token (1:8)

> 1 | import s{
    |         ^
  2 |             path: '/skeleton-welcome/welcome',
  3 |             name: 'skeleton-welcome/welcome',
  4 |             component: _15304950479044526b78913c1aab4524492713e5a560a

    at D:\multipage\node_modules\vue-skeleton-webpack-plugin\lib\ssr.js:89:24
    at compile (D:\multipage\node_modules\webpack\lib\Compiler.js:300:11)
    at applyPluginsAsync.err (D:\multipage\node_modules\webpack\lib\Compiler.js:510:14)
    at next (D:\multipage\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.<anonymous> (D:\multipage\node_modules\webpack\lib\CachePlugin.js:78:5)
    at Compiler.applyPluginsAsyncSeries (D:\multipage\node_modules\tapable\lib\Tapable.js:206:13)
    at compilation.seal.err (D:\multipage\node_modules\webpack\lib\Compiler.js:507:11)
    at Compilation.applyPluginsAsyncSeries (D:\multipage\node_modules\tapable\lib\Tapable.js:195:46)
    at applyPluginsAsync.err (D:\multipage\node_modules\webpack\lib\Compilation.js:683:19)
    at Compilation.applyPluginsAsyncSeries (D:\multipage\node_modules\tapable\lib\Tapable.js:195:46)
    at applyPluginsAsync.err (D:\multipage\node_modules\webpack\lib\Compilation.js:674:11)
    at Compilation.applyPluginsAsyncSeries (D:\multipage\node_modules\tapable\lib\Tapable.js:195:46)
    at applyPluginsAsync.err (D:\multipage\node_modules\webpack\lib\Compilation.js:669:10)
    at next (D:\multipage\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.<anonymous> (D:\multipage\node_modules\extract-text-webpack-plugin\dist\index.js:275:11)
    at Compilation.applyPluginsAsyncSeries (D:\multipage\node_modules\tapable\lib\Tapable.js:206:13)
```

**Comment by xiaoiver** [comment]
谢谢你的反馈，如果不需要这部分，可以直接从 `module` 中删除：
```javascript
// webpack.config.js

module: {
        rules: utils.styleLoaders({
            sourceMap: false,
            extract: true
        })
// 删掉下面的配置
.concat(SkeletonWebpackPlugin.loader({
            include: [
                resolve('src/pages/page1/entry.js'),
                resolve('src/pages/page2/entry.js')
            ],
            options: {
                entry: ['page1', 'page2'],
                routePathTemplate: '/[name]-skeleton',
                insertAfter: 'routes: [',
                importTemplate: 'import [name] from \'./[name].skeleton.vue\';'
            }
        }))
    },
```

**Comment by xiaoiver** [comment]
@martinko2009  `1.2.1` 版本之后已经支持了开发模式的 hot reload，所以可以移除 `SkeletonWebpackPlugin.loader` 这部分配置了。
